name: fruits_hub_dashboard
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0-323.0.dev

dependencies:
  cloud_firestore: ^6.0.2
  dartz: ^0.10.1
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  image_picker: ^1.2.0
  modal_progress_hud_nsn: ^0.5.1
  path: ^1.9.1
  skeletonizer: ^1.4.3
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
