// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2w7OLToXieG-1wMu58QkGlKe_qDJsnu0',
    appId: '1:421466721299:web:482ae9788e1a05bdb243e6',
    messagingSenderId: '421466721299',
    projectId: 'fruits-hub-20406',
    authDomain: 'fruits-hub-20406.firebaseapp.com',
    storageBucket: 'fruits-hub-20406.firebasestorage.app',
    measurementId: 'G-1TLRK9173F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvZCoNSBYg0ZzlYdPZmEwfVQxuRLBKdPo',
    appId: '1:421466721299:android:39ef931ebb9b5eeeb243e6',
    messagingSenderId: '421466721299',
    projectId: 'fruits-hub-20406',
    storageBucket: 'fruits-hub-20406.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKQawbHx2dE4U80b9rTWM03L_IFGWKL6g',
    appId: '1:421466721299:ios:db1599ef2f672e0fb243e6',
    messagingSenderId: '421466721299',
    projectId: 'fruits-hub-20406',
    storageBucket: 'fruits-hub-20406.firebasestorage.app',
    androidClientId: '421466721299-tmt45d726vdo8pj1o7raiblbv1ve11g5.apps.googleusercontent.com',
    iosClientId: '421466721299-jlgs45iuik83j60ii8e4hjh2g3engfer.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKQawbHx2dE4U80b9rTWM03L_IFGWKL6g',
    appId: '1:421466721299:ios:db1599ef2f672e0fb243e6',
    messagingSenderId: '421466721299',
    projectId: 'fruits-hub-20406',
    storageBucket: 'fruits-hub-20406.firebasestorage.app',
    androidClientId: '421466721299-tmt45d726vdo8pj1o7raiblbv1ve11g5.apps.googleusercontent.com',
    iosClientId: '421466721299-jlgs45iuik83j60ii8e4hjh2g3engfer.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2w7OLToXieG-1wMu58QkGlKe_qDJsnu0',
    appId: '1:421466721299:web:d5e2f7088f6af17cb243e6',
    messagingSenderId: '421466721299',
    projectId: 'fruits-hub-20406',
    authDomain: 'fruits-hub-20406.firebaseapp.com',
    storageBucket: 'fruits-hub-20406.firebasestorage.app',
    measurementId: 'G-1HF0TZ4LCG',
  );
}
